@Library('Shared') _
pipeline {
    agent any 
    
    environment {
        SONAR_HOME = tool "Sonar"
    }
    
    parameters {
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: '', description: 'Frontend Docker tag of the image built by the CI job')
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: '', description: 'Backend Docker tag of the image built by the CI job')
    }

    stages {

        stage("Validate Parameters") {
            steps {
                script {
                    if (params.FRONTEND_DOCKER_TAG == '' || params.BACKEND_DOCKER_TAG == '') {
                        error("FRONTEND_DOCKER_TAG and BACKEND_DOCKER_TAG must be provided.")
                    }
                }
            }
        }

        stage("Workspace cleanup") {
            steps {
                script {
                    cleanWs()
                }
            }
        }
        
        stage('Git: Code Checkout') {
            steps {
                script {
                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: '*/main']],
                        extensions: [[
                            $class: 'CloneOption',
                            shallow: true,
                            depth: 1,
                            timeout: 30
                        ]],
                        userRemoteConfigs: [[
                            url: 'https://github.com/Zohaibq112/wonderlust-v2.git',
                            credentialsId: 'Github-cred'
                        ]]
                    ])
                }
            }
        }
        
        stage("Trivy: Filesystem scan") {
            steps {
                script {
                    trivy_scan()
                }
            }
        }

        stage("OWASP: Dependency check") {
            steps {
                script {
                    owasp_dependency()
                }
            }
        }
        
        stage("SonarQube: Code Analysis") {
            steps {
                script {
                    sonarqube_analysis("Sonar","wanderlust","Zohaibq112_wonderlust-v2")
                }
            }
        }
        
        stage("SonarQube: Code Quality Gates") {
            steps {
                script {
                    sonarqube_code_quality()
                }
            }
        }
        
        stage('Exporting environment variables') {
            parallel {
                stage("Backend env setup") {
                    steps {
                        script {
                            dir("Automations") {
                                sh "bash updatebackendnew.sh || echo 'Skipped'"
                            }
                        }
                    }
                }
                stage("Frontend env setup") {
                    steps {
                        script {
                            dir("Automations") {
                                sh "bash updatefrontendnew.sh || echo 'Skipped'"
                            }
                        }
                    }
                }
            }
        }
        
        stage("Docker: Build Images") {
            steps {
                script {
                    dir('backend') {
                        docker_build("wanderlust-backend-beta","${params.BACKEND_DOCKER_TAG}","zohaib112")
                    }
                    dir('frontend') {
                        docker_build("wanderlust-frontend-beta","${params.FRONTEND_DOCKER_TAG}","zohaib112")
                    }
                }
            }
        }
        
        stage("Docker: Push to DockerHub") {
            steps {
                script {
                    docker_push("wanderlust-backend-beta","${params.BACKEND_DOCKER_TAG}","zohaib112") 
                    docker_push("wanderlust-frontend-beta","${params.FRONTEND_DOCKER_TAG}","zohaib112")
                }
            }
        }
    }

        post {
            success {
                script {
                    try {
                        archiveArtifacts artifacts: '*.xml', followSymlinks: false
                    } catch(Exception e) {
                        echo "No xml artifacts found - continuing"
                    }
                    build job: "Wanderlust-CD", parameters: [
                        string(name: 'FRONTEND_DOCKER_TAG', value: "${params.FRONTEND_DOCKER_TAG}"),
                        string(name: 'BACKEND_DOCKER_TAG', value: "${params.BACKEND_DOCKER_TAG}")
                    ]
                }
            }
        }
}